# Generated by Django 2.2.5 on 2021-03-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
